{
  "openapi": "3.1.0",
  "info": {
    "title": "DinDin API de Finanças Pessoais",
    "description": "A API de Finanças Pessoais é uma poderosa plataforma de gerenciamento financeiro que permite aos usuários controlar suas receitas e despesas de forma eficaz. Com esta API, os usuários podem se cadastrar, fazer login, gerenciar seus perfis, criar categorias personalizadas, registrar transações, consultar extratos e muito mais. A API garante a segurança dos dados e a privacidade do usuário, permitindo que cada usuário acesse apenas suas próprias informações.",
    "contact": {
      "nome": "Walter Netto",
      "email": "walter.netto@live.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api-dindin-ai2b.onrender.com/",
      "description": "Web Server"
    },
    {
      "url": "http://localhost:3000",
      "description": "Local Server"
    }
  ],
  "paths": {
    "/usuario": {
      "post": {
        "summary": "Criar um novo usuário",
        "description": "Rota responsável por criar um novo usuário",
        "tags": ["Usuários"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Usuario"
              },
              "examples": {
                "Usuário Exemplo 1": {
                  "value": {
                    "nome": "Walter Netto",
                    "email": "walter@example.com",
                    "senha": "senha123"
                  }
                },
                "Usuário Exemplo 2": {
                  "value": {
                    "nome": "Maria Silva",
                    "email": "maria@example.com",
                    "senha": "senha456"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Erro ao criar usuário"
          },
          "201": {
            "description": "Usuário criado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Usuario"
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Atualizar usuário",
        "description": "Rota responsável por editar informações de um usuário",
        "tags": ["Usuários"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Usuario"
              },
              "examples": {
                "Exemplo de Atualização de Usuário 1": {
                  "value": {
                    "nome": "José Silva",
                    "email": "jose@example.com",
                    "senha": "senha789"
                  }
                },
                "Exemplo de Atualização de Usuário 2": {
                  "value": {
                    "nome": "Helena Costa",
                    "email": "helena@example.com",
                    "senha": "senha789"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Não autorizado"
          },
          "404": {
            "description": "Usuário não encontrado"
          },
          "204": {
            "description": "OK"
          }
        }
      },
      "get": {
        "summary": "Detalhar usuário",
        "description": "Rota responsável por detalhar o usuário",
        "tags": ["Usuários"],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "401": {
            "description": "Não autorizado"
          },
          "400": {
            "description": "Erro ao buscar usuário"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Usuario"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "summary": "Realizar login",
        "description": "Rota responsável por autenticar um usuário registrado",
        "tags": ["Autenticação"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Usuario"
              },
              "examples": {
                "Exemplo de Login 1": {
                  "value": {
                    "email": "walter@example.com",
                    "senha": "senha123"
                  }
                },
                "Exemplo de Login 2": {
                  "value": {
                    "email": "maria@example.com",
                    "senha": "senha456"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Erro de autenticação"
          },
          "200": {
            "description": "Login bem-sucedido"
          }
        }
      }
    },
    "/transacao": {
      "post": {
        "summary": "Criar uma nova transação",
        "description": "Rota responsável por criar uma nova transação",
        "tags": ["Transações"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Transacao"
              },
              "examples": {
                "Exemplo 1": {
                  "value": {
                    "tipo": "entrada",
                    "descricao": "Salário",
                    "valor": 350000,
                    "data": "2022-03-24T15:30:00.000Z",
                    "categoria_id": 14
                  }
                },
                "Exemplo 2": {
                  "value": {
                    "tipo": "saida",
                    "descricao": "Aluguel",
                    "valor": 120000,
                    "data": "2022-03-25T12:00:00.000Z",
                    "categoria_id": 3
                  }
                },
                "Exemplo 3": {
                  "value": {
                    "tipo": "saida",
                    "descricao": "Supermercado",
                    "valor": 15000,
                    "data": "2022-03-26T10:15:00.000Z",
                    "categoria_id": 4
                  }
                },
                "Exemplo 4": {
                  "value": {
                    "tipo": "entrada",
                    "descricao": "Venda de Produtos",
                    "valor": 500000,
                    "data": "2022-03-27T14:45:00.000Z",
                    "categoria_id": 15
                  }
                },
                "Exemplo 5": {
                  "value": {
                    "tipo": "entrada",
                    "descricao": "Bônus",
                    "valor": 100000,
                    "data": "2022-03-28T09:00:00.000Z",
                    "categoria_id": 16
                  }
                },
                "Exemplo 6": {
                  "value": {
                    "tipo": "saida",
                    "descricao": "Transporte Público",
                    "valor": 5000,
                    "data": "2022-03-29T08:30:00.000Z",
                    "categoria_id": 13
                  }
                },
                "Exemplo 7": {
                  "value": {
                    "tipo": "saida",
                    "descricao": "Restaurante",
                    "valor": 8000,
                    "data": "2022-03-30T19:00:00.000Z",
                    "categoria_id": 8
                  }
                },
                "Exemplo 8": {
                  "value": {
                    "tipo": "entrada",
                    "descricao": "Presente de Aniversário",
                    "valor": 5000,
                    "data": "2022-03-31T14:00:00.000Z",
                    "categoria_id": 10
                  }
                },
                "Exemplo 9": {
                  "value": {
                    "tipo": "saida",
                    "descricao": "Medicamentos",
                    "valor": 3000,
                    "data": "2022-04-01T10:30:00.000Z",
                    "categoria_id": 12
                  }
                },
                "Exemplo 10": {
                  "value": {
                    "tipo": "saida",
                    "descricao": "Internet",
                    "valor": 6000,
                    "data": "2022-04-02T16:30:00.000Z",
                    "categoria_id": 2
                  }
                }
              }
            },
            "responses": {
              "400": {
                "description": "Erro ao criar transação"
              },
              "201": {
                "description": "Transação criada com sucesso",
                "content": {
                  "application/json": {
                    "schema": {
                      "$ref": "#/components/schemas/Transacao"
                    }
                  }
                }
              },
              "500": {
                "description": "Erro no servidor",
                "content": {
                  "application/json": {
                    "example": {
                      "mensagem": "Erro no servidor."
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "Usuario": {
        "type": "object",
        "properties": {
          "nome": {
            "type": "string",
            "description": "O nome do usuário."
          },
          "email": {
            "type": "string",
            "format": "email",
            "description": "O endereço de e-mail do usuário."
          },
          "senha": {
            "type": "string",
            "description": "A senha do usuário."
          }
        },
        "required": ["nome", "email", "senha"]
      },
      "Transacao": {
        "type": "object",
        "properties": {
          "tipo": {
            "type": "string",
            "enum": ["entrada", "saida"],
            "description": "O tipo da transação (entrada ou saída)."
          },
          "descricao": {
            "type": "string",
            "description": "A descrição da transação."
          },
          "valor": {
            "type": "number",
            "description": "O valor da transação."
          },
          "data": {
            "type": "string",
            "format": "date",
            "description": "A data da transação (no formato 'YYYY-MM-DD')."
          },
          "categoria_id": {
            "type": "integer",
            "description": "O ID da categoria da transação."
          }
        },
        "required": ["tipo", "descricao", "valor", "data", "categoria_id"]
      }
    }
  }
}
